### ISSUE TITLE
[FEAT] Firebase 앱 연동

### ISSUE THREAD

**Issue by KkamSonLee** [Team-AngDroid/Refrigerator_Management#1]
## 🔈 Issue

- 파베랑 앱이랑 연동 해놓으려구 합니당

## 📑 To-do

- [x] 파베 프로젝트 생성
- [x] json 파일 받기
- [x] 프로젝트 수준 폴더에 삽입
- [x] sync 확인
