### ISSUE TITLE
[FEAT] Domain 로직 시작 전 성능 개선

### ISSUE THREAD

**Issue by KkamSonLee** [Team-AngDroid/Refrigerator_Management#15]
## 🔈 Issue

- 해당 링크를 통해서 MultiView Type을 수정해보려고 합니다.
- Sealed Class를 통해서 원래 해결할 수 있다고는 들었었는데, 마땅히 방법이 떠오르지 않다가 해당 링크를 보니 해결 할 수 있을 것 같습니다 ㅎㅎ 이것까지만 적용해보고 안되면 이슈 그냥 닫겠습니다 ㅎ
https://medium.com/%EB%B0%95%EC%83%81%EA%B6%8C%EC%9D%98-%EC%82%BD%EC%A7%88%EB%B8%9[…]95%98%EA%B2%8C-%EC%A0%95%EC%9D%98%ED%95%98%EA%B8%B0-e2d9dbbd386

## 📑 To-do

- [x] converting interface type to sealed class type
- [x] business logic 정상 작동 확인
- [x] list adapter 정상 작동 확인
