### ISSUE TITLE
[REMOTE] 파베 연동 (냉장고 뷰)

### ISSUE THREAD

**Issue by KkamSonLee** [Team-AngDroid/Refrigerator_Management#20]
## 🔈 Issue

- 냉장고 부분은 파베 연동 해보면 좋을듯 합니다.
- 빠르다고 생각할수도 있지만, 한 명이 먼저 해놔야 다음 사람이 편할듯하네요

## 📑 To-do

- [x] Service 클래스 생성
- [x] Service에 파베 연동
- [x] 파베에 더미 데이터 삽입
- [x] Hilt 주입
- [x] 데이터 정상으로 넘어오는지 확인
