### ISSUE TITLE
[FEAT] 식재료 Detail View, Firebase Recipe Processing

### ISSUE THREAD

**Issue by KkamSonLee** [Team-AngDroid/Refrigerator_Management#25]
## 🔈 Issue

- 식재료 디테일 뷰 만들려고 합니다.
- 해당 이슈는 레시피쪽 리스트 출력까지만 하는 용도의 이슈입니다.
- 추가적으로 레시피쪽도 건드릴려고 합니다.

## 📑 To-do

- [x] 이미지 등의 리소스 추가
- [x] 레시피 아이템 레이아웃 생성
- [x] 어댑터 생성 (Dynamic Span Text Color 적용)
- [x] 파이어베이스 레시피 연동
