### ISSUE TITLE
[FEAT] 중간 보고서용 시연 Flow 식재료 Detail 뷰 만들어놓기

### ISSUE THREAD

**Issue by KkamSonLee** [Team-AngDroid/Refrigerator_Management#29]
## 🔈 Issue

- 식재료 Detail 뷰를 완성 하려고 합니다!!
- 일단 보여주기용을 목표로 합시다!

## 📑 To-do

- [x] 아이템 레이아웃 만들기
- [x] 어댑터 만들기
- [x] 파베에서 특정 식재료의 리스트만 받아오기 로직 구현
- [x] 뷰 구성
- [x] 스크롤 처리 해결
