### ISSUE TITLE
[FEAT] Data Layer 관련 클래스 생성 예정입니다.

### ISSUE THREAD

**Issue by KkamSonLee** [Team-AngDroid/Refrigerator_Management#3]
## 🔈 Issue

- Data Layer에 들어갈 Dto, Mapper, repositoryImpl 등을 일단 기본 틀을 짜놓으려고 합니다.
- 기본틀을 짜는 기준은 Firebase FireStore Document-Collection 기준으로 작성하려고 합니다.
- 가장 root에 존재하는 Document들인 Recipe, Food, User을 기반으로 response를 Dto로 두고 작업하려고 합니다.

## 📑 To-do

- [x] 더미 데이터 삽입
- [x] Dto 생성
- [x] Dto to Entity Mapper 생성
- [x] RepositoryImpl 목적에 맞게 분리
- [x] hilt firestore ref Inject, snapshot document Inject
- [x] 나머지 hilt 작업
