### ISSUE TITLE
[FEAT] 냉장고탭 성능 개선, 식재료 detail 기능 추가

### ISSUE THREAD

**Issue by KkamSonLee** [Team-AngDroid/Refrigerator_Management#34]
## 🔈 Issue

- 냉장고 탭 불러올 때 다른 탭 클릭 시 꺼지는 경우가 있어서 처리를 하려고 합니당
- 식재료 detail에서 남은 기간에 따라서 텍스트를 다르게 주려고 합니다.

## 📑 To-do

- [x] job cancel 처리
- [x] 냉장고 뷰 개수 처리 부분 텍스트 Color 변경 처리
- [x] 식재료들의 Default 유통기한 정하기
- [x] 남은 기간 처리
- [x] 기간 지난거 데이터 안 받아오기
- [x] 기간 지난거 자동 삭제 처리
