### ISSUE TITLE
[Chore] 앱 아이콘, 스플래시 뷰

### ISSUE THREAD

**Issue by KkamSonLee** [Team-AngDroid/Refrigerator_Management#35]
## 🔈 Issue

- 앱 아이콘과 스플래시 뷰 넣으려 합니다!

## 📑 To-do

- [x] 앱 아이콘 선정 및 리소스 추가
- [x] 스플래시 Lottie File 선택
- [x] Lottie 적용
- [ ] 스플래시에서 초기 유저 데이터 받아오기
