### ISSUE TITLE
[FEAT] 콜백기반 FireStore Call 동기 처리로 변경, 의존성 주입

### ISSUE THREAD

**Issue by KkamSonLee** [Team-AngDroid/Refrigerator_Management#43]
## 🔈 Issue

- 코루틴을 사용하여 FireStore 데이터 받아오는 로직을 Listener에서 동기처리로 변경 하려고합니다.
- 파베도 의존성 주입하려고 합니다.

## 📑 To-do

- [x] Gradle 라이브러리 추가
- [x] 외부 레퍼런스 참고
- [x] App 파일 필드 최대한 제거
- [x] 의존성 주입
- [x] Layer별로 파라미터 변경
- [x] 잘 작동하는지 확인
