### ISSUE TITLE
[FEAT] 추가 될 Food에 대한 처리

### ISSUE THREAD

**Issue by KkamSonLee** [Team-AngDroid/Refrigerator_Management#48]
## 🔈 Issue

- ML에서 인식시킬 데이터 추가로 인한 이슈입니다.
- 그김에 제 담당 ViewModel 생성자 파라미터 Repository to UseCase 적용시켜놓으려합니다.

## 📑 To-do

- [x] Firestore 오렌지, 포도, 바나나, 망고, 키위 추가
- [x] Default Image 추가
- [x] Food Id 개편
- [x] UseCase 수정
- [x] 정상 작동 확인
