### ISSUE TITLE
[FEAT] 식재료 추가 로직 개발

### ISSUE THREAD

**Issue by KkamSonLee** [Team-AngDroid/Refrigerator_Management#50]
## 🔈 Issue

- Firebase Storage 사용하여 식재료 추가시 CameraX로 넘어오는 List<ByteArray > 객체들을 Storage에 추가하는 작업을 하려고 합니당
- 아직 카메라 연동이 되어이지 않으므로 더미 데이터로 테스트해보겠습니다;.

## 📑 To-do

- [x] Firebase Storage 폴더링
- [x] List of ByteArray to List of Bitmap mapper 구현
- [x] List of ByteArray compress 구현 (용량이 너무 크면 안 됨, 저장 파일 타입 통일)
- [x] Storage 상에서 받아온 이미지 uri download 
- [x] 재료 추가 완료 시, Firestore와 Firebase Storage imagePath Mapping
- [x] 재료 추가 로직 구현
- [ ] 정상 작동 확인
