### ISSUE TITLE
[FEAT] 리스트 어댑터 멀티뷰홀더 적용

### ISSUE THREAD

**Issue by KkamSonLee** [Team-AngDroid/Refrigerator_Management#6]
## 🔈 Issue

- 멀티뷰홀더 부시려고 합니다.

## 📑 To-do

- [x] 리스트 카테고리별 정렬
- [x] 카테고리 데이터 클래스 중간에 삽입
- [x] 리스트 어댑터 제대로 되는지 확인

**Comment by IslandofDream** [comment]
https://medium.com/@alirezarzna/creating-a-grid-list-with-section-headers-using-recyclerview-87a4affc05e

GridLayout관련 동적 span count 변환

**Comment by KkamSonLee** [comment]
감사합니당~!!!
