### ISSUE TITLE
[FEAT] 안 쓰는 코드 정리

### ISSUE THREAD

**Issue by KkamSonLee** [Team-AngDroid/Refrigerator_Management#60]
## 🔈 Issue

- 자바 language 40% -> 0%로 만들려고 합니다.

## 📑 To-do

- [x] 자바 파일 제거
- [x] 자바 파일 to 코틀린 파일 변환
- [x] 안 쓰는 파일 제거
